### ISSUE TITLE
Windows plugins v1.1 not seen by Audacity or Sonic Visualiser 

### ISSUE THREAD

**Issue by windinthew** [bbcrd/bbc-vamp-plugins#3]
V1.1 for Windows ( https://github.com/bbcrd/bbc-vamp-plugins/releases/download/v1.1/Windows.zip on https://github.com/bbcrd/bbc-vamp-plugins/releases ) is not seen by Audacity 2.1.0 or Sonic Visualiser 2.4.1 on Windows 7 x64 when the three extracted plugin files are placed in C:\Program Files (x86)\Vamp Plugins.   

Audacity is a 32-bit app and sees the v1 plugins fine. 

Sonic Visualiser reports that "bbc-vamp-plugins.dll" is not meant for Windows or contains an error.

**Comment by chrisbaume** [comment]
Broken release has been fixed.
