### ISSUE TITLE
Should "Linux.64-bit.gz" be renamed "Linux.64-bit.tar.gz"?

### ISSUE THREAD

**Issue by SamuelMiller** [bbcrd/bbc-vamp-plugins#4]
Interestingly, I wasn't able to properly extract the Linux.64-bit binary vamp package until I changed the downloaded file name from "Linux.64-bit.gz" to "Linux.64-bit.tar.gz" in Linuxmint 17.02  OS.

**Comment by chrisbaume** [comment]
Thanks for spotting that.
